server:
  servlet:
    session:
      timeout: 120m
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      test-on-connect: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect


  quartz:
    job-store-type: jdbc
    jobStore:
    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

uploads:
  upload-directory: docs-upload
